{"name": "test_user_login_normal", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'get'", "trace": "self = <testcase.test_login.TestLogin object at 0x03DC6E90>\n\n    @allure.link('/basic/auth/login', name='登录页面')\n    @allure.story(\"测试登录成功\")  # 功能块，具有相同feature或story的用例将规整到相同模块下,执行时可用于筛选\n    def test_user_login_normal(self):\n        case_data = get_test_data(self.excel_data,'userloginnormal')  # 从数据列表中查找到该用例数据\n>       res = send_request(case_data)\n\ntestcase\\test_login.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncase_data = None\n\n    def send_request(case_data):  # 传递用例数据，发送请求\n>       url = case_data.get('url')\nE       AttributeError: 'NoneType' object has no attribute 'get'\n\ncommen\\send_request.py:25: AttributeError"}, "start": 1600240936558, "stop": 1600240936558, "uuid": "635bf620-2bed-4c62-a925-c59e3ba15907", "historyId": "b031943916688f96acb8a4379a6596b4", "testCaseId": "4235acd3debbc3714fcb1008276905ef", "fullName": "testcase.test_login.TestLogin#test_user_login_normal", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "测试登录模块"}, {"name": "story", "value": "测试登录成功"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TX5C3S1L7D31UYD"}, {"name": "thread", "value": "21264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}], "links": [{"type": "link", "url": "/basic/auth/login", "name": "登录页面"}]}